// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOhzrZ9fwnNe8IeXXPMCNDaijb0jez0eo',
    appId: '1:970057154500:web:90ca5360d9f5c22b8cae91',
    messagingSenderId: '970057154500',
    projectId: 'instagram-test-6e985',
    authDomain: 'instagram-test-6e985.firebaseapp.com',
    storageBucket: 'instagram-test-6e985.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv20fU69Hx3MaVMTtMSHYwZ0PXCKe1YBM',
    appId: '1:970057154500:android:2779f444d6ab78d18cae91',
    messagingSenderId: '970057154500',
    projectId: 'instagram-test-6e985',
    storageBucket: 'instagram-test-6e985.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbH4lKYtlJ_04FTVLfGtS8HQqf2cjD-zw',
    appId: '1:970057154500:ios:16c0208a980ee0688cae91',
    messagingSenderId: '970057154500',
    projectId: 'instagram-test-6e985',
    storageBucket: 'instagram-test-6e985.appspot.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbH4lKYtlJ_04FTVLfGtS8HQqf2cjD-zw',
    appId: '1:970057154500:ios:f8cb6b9e5692cbba8cae91',
    messagingSenderId: '970057154500',
    projectId: 'instagram-test-6e985',
    storageBucket: 'instagram-test-6e985.appspot.com',
    iosBundleId: 'com.example.instagram.RunnerTests',
  );
}
